info:
  build:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    profile: dev

logging:
  level:
    org:
      springframework:
        security: INFO
        web:
          client: INFO
      hibernate:
        SQL: DEBUG
    io:
      ucandoit: DEBUG

spring:
  datasource:
#    url: jdbc:postgresql://ucandb.cogsjd1upa8j.eu-central-1.rds.amazonaws.com:5432/magic
    url: jdbc:postgresql://localhost:5432/magic
    username: magic
    password: magic
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

server:
  contextPath: /magic-back

magic:
  api:
    baseUrl: https://api.magicthegathering.io/v1/
    endpoint:
      sets: sets
      cards: cards